templates/frontend/_localeswitcher.twig

Don't assume that bolt is mounted on the root, use the urlgenerator for homepage link.
Fixes #36

fix localeswitcher for subfolders

---

src/Frontend/LocalizedFrontend.php
src/Frontend/LocalizedMenuBuilder.php
src/TranslateExtension.php

Fixes LocalizedMenuBuilder's missing reference to Lib::path, by copying bolt's private function `resolveRouteToLink()` and referring to this function instead.
Fixes: #42

Fix LocalizedMenuBuilder's missing reference to Lib::path

---

src/Field/LocaleField.php
src/Frontend/LocalizedFrontend.php
src/Frontend/LocalizedMenuBuilder.php
src/Provider/FieldProvider.php
src/Storage/ContentTypeTable.php
src/Storage/Legacy.php
src/TranslateExtension.php

@SahAssar this is probably of most interest to you.
A few things:
* `$config` is deliberately a private variable, as YAML loading depends on getConfig() being called
* `$app` is the same, don't set/use a `$this->app` in the loader … that is not what it is there for
* Avoid using `$app['request']` where ever possible, it will be populated regardless of where in the request cycle you are … the request stack however only gets set at the beginning of said cycle
* Always develop extensions with `E_ALL`, developer notices, and Twig strict variables turned on, or you have :koala: PRs :laughing:

Clean up and corner case bug fixes

---

src/Frontend/LocalizedFrontend.php
src/TranslateExtension.php

* Removed default _locale in routing. Instead, extended url_generator to make sure _locale is always available as a parameter (for 404's). Fixes: #47
* Use `reset($config->getLocales());` instead of `current` to get the first entry.
* Fixed typo in code.

Fix homepage redirect and _locale on 404's

---

config/config.yml.dist
src/Config/Config.php
src/EventListener/StorageListener.php
src/Frontend/LocalizedFrontend.php
src/Frontend/LocalizedMenuBuilder.php
src/TranslateExtension.php
templates/fields/_locale.twig
templates/frontend/_localeswitcher.twig

* Fix request cycle issues with the default locale in the routing override
* Move the homepageredirect to the top of the routes, fixes #47
* Add requirements to all routes based on the locales configured to avoid DC issues
* fix a few typos/minor errors
* Change how we look for the locale param so that it is allowed in a query string (required for preview and editcontent), fixes #46
* Add in a js to add the icon to repeaters, fixes #41
* Actually get the localeSlug in the StorageListener, (ping @gawainlynch for better way to do it since it comes from the request)
* Fix PSR2 warning for line length
* Ensure consistent usage between `current.get('slug')` and `current.slug`

Fix #47, #46 and #41 among other small issues

---

config/config.yml.dist
src/Config/Config.php
src/Routing/LocalizedUrlGenerator.php
src/TranslateExtension.php

Use the `Accept-Language` header to determine the best locale, if the `_locale` parameter is not set in the url. More precisely:
* Redirect `/` to the preferred locale, using the `Accept-Language` header, instead of redirecting to the first locale set in the configuration.
* Render 404 responses in the preferred locale using the `Accept-Language` header, instead of the first locale set in the configuration.
* All urls starting with `/{_locale}` have unchanged behaviour, they ignore the `Accept-Language` header.
Two remarks:
* Negotiating is based on Symfony's `Symfony\Component\HttpFoundation\Request::getPreferredLanguage`. This function needs an array of the supported locales on the website. In my current implementation, I supply both `en_GB` and `en` if `en_GB` is set in the …

Redirect to locale based on Accept-Language header

---

src/Frontend/LocalizedFrontend.php

We don't need execute DB query if slug is numeric or translate slug is disabled.

Small speed-up if translate slug is disabled

---

README.md
src/Config/Locale.php

Implement ArrayAccess in Locale to allow the locales array to be ordered with `|order()`.
For example, if one always wants to have the active locale first:
```
<ul{% if classes %} class="{{ classes }}"{% endif %}>
{% for locale in locales|order('-active') %}
<li{% if locale.get('active') %} class="active"{% endif %}>
<a title="{{ locale.get('label') }}" href="{{ locale.get('url') }}">
{{ locale.get('label') }}
</a>
{% endfor %}
</ul>
```
This fixes the other question mentioned in #61: "how do i get the active locale first without looping twice?" and was also mentioned way back in #5
@madc Please have a look and merge if you feel this looks okay

Implement ArrayAccess in Locale to allow |order() in twig

---

src/Config/Config.php
src/Config/Locale.php
src/EventListener/StorageListener.php
src/Storage/ContentTypeTable.php
src/Storage/Legacy.php

This fixes #57.
Keep in mind that since hydration for templatefields in repeaters didn't land until bolt/bolt#5670 in core this won't work on current stable, only on release/3.0 or master (or release/3.1).
@madc You know the drill :wink:

Hydrate repeaters in templatefields

---

src/EventListener/StorageListener.php
src/Storage/Legacy.php

When a new record is created, the <locale>data field for non-default locales are empty. This PR avoids an exception in this case.
@SahAssar Are you OK with that?
Fixes: #89

Fixing issue with empty _data field

---

templates/fields/_locale.twig

We've had a case where a client's translator messed up the entire DB, by replacing the correct content with the translated ones. Apparently, they got confused about which was the "current" selected language. 
This PR changes the look of the button to mimic that of an active tab, instead of a deactivated one. The pull down also makes it more clear which is the selected language. 
Before: 
After:

Tweak the looks of the tab.

---

config/config.yml.dist
src/Config/Config.php
src/EventListener/LocaleListener.php
src/TranslateExtension.php

At this moment, Silex sets the request locale and the variable `$app['locale']` to the value `$request->get('_locale')`. However, the latter only contains the locale slug (e.g. "en") and not the locale name (e.g. "en_US"). The added file `LocaleListener.php` fixes this. 
Together with the addition of the code in `TranslateExtension.php` which loads the translator resources for all locales, this enables the built in translator to translate standard messages in the appropriate language. 
Note that for testing purposes on an existing installation of bolt, it might be necessary to clean the directory `app/cache/trans` manually.

Set $app['locale'] to locale name instead of locale slug

---

src/Field/LocaleDataField.php
src/Field/LocaleField.php

Extending FieldTypeBase in the two field classes ensures that the fields also implement FieldTypeInterface which is checked for across the Bolt 3.3 codebase.
Fixes: bolt/bolt#6840

[Bolt 3.3 Compatibility] Implement the new Field Type Interface

---

src/Storage/Legacy.php

When you have more than one repeater in a contenttype, it rises a FieldConfigurationException.
Initializing $originalMapping array resolves the issue.
A brief description of the Pull Request goes here.
Related:  https://github.com/bolt/bolt/issues/5533

Fix bug in Legacy.php

---

README.md
config/config.yml.dist
src/EventListener/StorageListener.php
templates/fields/_locale.twig

Fix misspellings of translateable but allow the old for now.
Also shorten `is_translateable` to `translatable` to make it more aligned with `sortable` and so on.
Fixes #135
@lenvanessen sounds good to you?

Fix misspellings but allow the old for now

---

src/EventListener/StorageListener.php

Fixes #128 
When you add fields to the ContentType, after initially creating them, they don’t exist in the old dataset, until you open the entry and save it. This means translate was trying to grab an array index that isn't actually there, resulting in a undefined index error.

Fixes #128

---

src/Storage/Legacy.php

Can be accessed in twig using {{ record.originalValues }}

Make original record values available in twig from any locale

---

docs/overrides.md
src/Frontend/LocalizedFrontend.php

Option to disable the global automatic routing override on a route
while still enabling it for the other routes.
Use case: while translating an existing site, one might want to serve both `/page` and `/{_locale}/page` while using the global automatic locale override, without the hassle of having to switch it off and redefine the whole routing for all translatable content types.

Selectively disable automatic routing override on a route basis

---

src/Frontend/LocalizedFrontend.php

Make sure we have a requirements/_locale key in a route before blindly checking it against a string.
This would result in notices thrown about missing indices. If the key isn't set at all in the route, we
should just blindly apply the default.

Fix notices about missing indices

---

templates/fields/_locale.twig
templates/fields/_locale_data.twig

Hide the hidden fields completely in the backend, instead of displaying the default margins.

Hide hidden fields

---

src/Frontend/LocalizedFrontend.php

Record frontend controller incorrectly handles non-existing records. Atm, if you try accessing /entry/non-existing-entry if entry is translatable, instead of 404 you'll be redirected to the alphabetically first entry in the database. I added a condition that checks if the entered slug is actually present in the database, and if not, then it displays the 404 page.

Fix incorrect routing of non-existing records

---

templates/fields/_locale.twig

I've encountered a few usecases where I'd like the localelink to switch to the same tab in the other language. When an editor asked for it I decided to try and add that to the extension. See what you think!

Remember tab when switching locale

---

docs/example.md

without the a "locale" field type defined in a content type, the locale switcher is not displayed when editing a content type

add missing locale field type

---

src/EventListener/StorageListener.php

The event did not contain the correct contenttype slug, which resulted in empty language data/slug fields.
Fixes: #173

Fixed a bug where the translation data was not saved if the slug did not match the generated slug
