- src/TranslateExtension.php
- templates/frontend/_localeswitcher.twig
Simplified the localeswitcher template.
Fixes: #30 
Refs: #14
> Moved logic from template to php

- composer.json
- src/Config/Config.php
- src/Config/Locale.php
- src/EventListener/StorageListener.php
- src/Frontend/LocalizedFrontend.php
- src/Storage/ContentTypeTable.php
- src/TranslateExtension.php
- templates/fields/_locale.twig
@SahAssar you are far more familiar with the functionality, so please let me know if something isn't working as expected (it will also probably then hit us internally :wink:), and I will get onto it.
I killed off a few things in the request handling by pushing the local selection to a service, but I think the original assumptions were made on things "Not Quite Right" in Bolt 2.
> Koala — Round 2

- README.md
- src/EventListener/StorageListener.php
- src/Frontend/LocalizedFrontend.php
- src/TranslateExtension.php
Mostly stuff that appeared when working with `debug_error_level: -1`.
> Some minor changes / cleanup.

- README.md
Hi, great module! Working with it now for a new website. Just added some more info in the readme to get started. This can save others from searching for it too much
> Added some more info in README

- docs/homepage redirect.md
I've fleshed out the explanation from the issue tracker, and formatted it in Markdown.  If you notice anything amiss, I'll be happy to fix it up.  Might be worth copying the docs into the wiki area once they've been collected?  Let me know if there's anything else I should write up!
Fixes: #77
> Added homepage redirect docs

- src/TranslateExtension.php
> Default fallback to slug, to prevent it from being empty.

- src/EventListener/StorageListener.php
This fixes some errors we had with `debug_error_level: -1`. Please verify that my boolean logic is correct. :-)
> Prevent exceptions for sites with strict settings.

- README.md
Maybe this would have prevented  my mistake today.
[Prefix your PR title with [WIP], if it's a 'work in progress', or if you're looking for feedback before merging.]
A brief description of the Pull Request goes here.
Fixes: #1555 (please refer to an existing issue number, that this PR fixes)
> Give more indications where the hidden fields should go

- templates/fields/_locale.twig
replaced use of url function with use of path function to fix issue #113
Fixes: #113
> replaced use of url function with use of path function to fix issue #113

- src/EventListener/StorageListener.php
- src/Storage/Legacy.php
Refer to #127 for the original fix.
> Fix formatting of @nealmarques 's PR

- src/EventListener/StorageListener.php
Just updating one of our projects we got into the issue 130. @bobdenotter did some debug and fixed it.
This PR fixes #130
> Add isset() check for $values['_locale']

- src/Frontend/LocalizedFrontend.php
> Fix listings

- src/EventListener/StorageListener.php
Fixes issue where you have the templatefield-select set to is_translateable, but don't have any actual templatefields defined
> Fixex non-defined templatefields

- templates/frontend/_localeswitcher.twig
Hi @SahAssar I immediately open a PR if it can be fixed like this.
Fixes #152
> Add default twig filter on locales

- src/Storage/Legacy.php
Fix for Bolt 3.6 compatibility. Thank you, @yawicz
See: https://github.com/bolt/bolt/issues/7688
> Compatibility fix for Bolt 3.6

- composer.json
Make sure we only get this on Bolt 3.6+
> Update for Bolt 3.6

- docs/repeaters.md
The URL pointed to the old repository
> Fix issue URL to the new repository

- src/Storage/Legacy.php
Fix for field type blocks. Prevent from getting "__internal" error on blocks.
> Fix for field type blocks

- src/EventListener/StorageListener.php
Check if the contentType is null, to prevent warnings.
> Check if the contentType is null

- docs/localeswitcher-anywhere.md
> add missing link to referenced issue

- src/Frontend/LocalizedFrontend.php
Fixed the "Trying to access array offset on value of type bool" error if no slug was found in the database
> Fixed a bug where the 404 page did throw an array offset error
